services:
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile-app 
  todo-service:
    build: 
      context: .
      dockerfile: Dockerfile
  todo-migration:
    build: 
      context: .
      dockerfile: Dockerfile-migration