# Stage 1: Build the application
FROM node:20 AS build

WORKDIR /app

COPY ./app /app/

RUN npm install
RUN npm run build -- --configuration=production

# Stage 2: Serve the built application with Nginx
FROM nginx:latest

## Remove the default Nginx configuration
RUN rm -rf /etc/nginx/conf.d/*

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

## Copy the built Angular application files to the Nginx default HTML directory
COPY --from=build /app/dist/todo /app/dist/todo/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# CMD ["tail", "-f", "/dev/null"]