insert into user_tasks (user_name, description, completed)
values
('thanos@email.test', '(01) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of typed and scrambled it to make an type specimen book', false),
('thanos@email.test', '(02) Lorem Ipsum is simply dummy text of the printing', true),
('thanos@email.test', '(03) Lorem Ipsum is simply dummy text of the printing', true),
('thanos@email.test', '(04) Lorem Ipsum is simply dummy text of the printing', true),
('thanos@email.test', '(05) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(06) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(07) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(08) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(09) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(10) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(11) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(12) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(13) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(14) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(15) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(16) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(17) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(18) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(19) Lorem Ipsum is simply dummy text of the printing', false),
('thanos@email.test', '(20) Lorem Ipsum is simply dummy text of the printing', false),

('thor@email.test', '(01) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of typed and scrambled it to make an type specimen book', false),
('thor@email.test', '(02) Lorem Ipsum is simply dummy text of the printing', true),
('thor@email.test', '(03) Lorem Ipsum is simply dummy text of the printing', true),
('thor@email.test', '(04) Lorem Ipsum is simply dummy text of the printing', true),
('thor@email.test', '(05) Lorem Ipsum is simply dummy text of the printing', false),
('thor@email.test', '(06) Lorem Ipsum is simply dummy text of the printing', false),
('thor@email.test', '(07) Lorem Ipsum is simply dummy text of the printing', false),
('thor@email.test', '(08) Lorem Ipsum is simply dummy text of the printing', false),
('thor@email.test', '(09) Lorem Ipsum is simply dummy text of the printing', false),
('thor@email.test', '(10) Lorem Ipsum is simply dummy text of the printing', false),

('loki@email.test', '(01) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of typed and scrambled it to make an type specimen book', false),
('loki@email.test', '(02) Lorem Ipsum is simply dummy text of the printing', true),
('loki@email.test', '(03) Lorem Ipsum is simply dummy text of the printing', true),
('loki@email.test', '(04) Lorem Ipsum is simply dummy text of the printing', true),
('loki@email.test', '(05) Lorem Ipsum is simply dummy text of the printing', false);